### ISSUE TITLE
drone unity

### ISSUE THREAD

**Issue by bbhxwl** [game-ci/docker#192]
What command can be used to compile the program used by Windows?

```
kind: pipeline
type: docker
name: autoUpload
node:
  name: nas-runner
steps:
  - name: 自动编译
    image: unityci/editor:2021.3.13f1-base-1.0.1
    commands:
      - ls
      - unity-editor help
```
