### ISSUE TITLE
uname command not found

### ISSUE THREAD

**Issue by xibz** [game-ci/docker#92]
Updated to use `game-ci/unity-test-runner@v2` instead of `webbertakken/unity-test-runner@v2.0-alpha-1` and saw that it was unable to find any of the tests. Further it shows the test passing with 0/0 even though there is a compiler error provided down below

```
-----CompilerOutput:-stdout--exitcode: 136--compilationhadfailure: True--outfile: Temp/Assembly-CSharp-Editor.dll
-----CompilerOutput:-stderr----------
/opt/unity/Editor/Data/Tools/RoslynScripts/unity_csc.sh: line 23: uname: command not found
Failed to load H(~, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/opt/unity/Editor/Data/Tools/Roslyn/libcoreclr.so'
-----EndCompilerOutput---------------
```

I am using Unity `2019.4.22f1` along with this yaml file for my github action

```yaml
name: Unity Test Runner

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

on: [push, pull_request]

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2019.4.22f1
        testMode:
          - playmode
          - editmode
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: false # will be true eventually
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - name: Tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} Test Results
          customParameters: '-nographics'
```

I expected to see the step to fail along and also not a uname not found error :x
